name: CI test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  test_job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        organism:
          - "staphylococcus_aureus"
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Print Debug Info
        run: |
          SHORT_ORG=$(echo "${{ matrix.organism }}" | awk -F'_' '{print substr($1,1,1) $2}')
          make ${SHORT_ORG}_all


